# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OLink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  pod 'Resolver'
  pod 'Disk'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'OLinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OLinkUITests' do
    # Pods for testing
  end

end
